development: &default
  adapter: postgresql
  encoding: unicode
  database: app_prototype_development
  host: localhost
  port: <%= ENV["BOXEN_POSTGRESQL_PORT"] %>

test:
  <<: *default
  database: app_prototype_test
  min_messages: warning

staging:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
